<?php

namespace AppBundle\Repository;

/**
 * DisponibilidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisponibilidadRepository extends \Doctrine\ORM\EntityRepository
{
}
